
<footer class="footer">

    <div class="pull-left">
        <div>By Kyle Pollock</div>
        <div>University of Rochester '18</div>
        <div><a href="mailto:kpolloc3@u.rochester.edu">kpolloc3@u.rochester.edu</a></div>

    </div>

    <div class="pull-right align-right">
        <div>Follow me on: </div>
        <div class="social">
            <a href="https://www.github.com/ElusiveSemicolon">
                <i class="fab fa-github" aria-hidden="true"></i>
            </a>
            <a href="https://www.linkedin.com/in/kyle-pollock/">
                <i class="fab fa-linkedin" aria-hidden="true"></i>
            </a>
            <a href="https://www.facebook.com/kyle.pollock.14">
                <i class="fab fa-facebook" aria-hidden="true"></i>
            </a>
        </div>
    </div>

</footer>
