
<!--
The .is-current class depends on the menu-highlighter.js script in inc/scripts.inc
!-->

<!-- Bulma -->

<nav class="navbar" aria-label="main navigation">

    <!-- navbar-brand is main icon on left side -->
    <div class="navbar-brand">

      <!-- navbar-burger is only visible on mobile -->
      <button class="button navbar-burger" data-target="navMenu">
        <span></span>
        <span></span>
        <span></span>
      </button>

    </div>

    <!-- navbar-menu is only visible on desktop (or when toggled by burger)-->
    <div class="navbar-menu" id="navMenu">

      <div class="navbar-end">
        <!-- navbar items that go on right side -->
        <a class="navbar-item" href="index.php">Home</a>
        <a class="navbar-item" href="zabaziz.php">Zubair Aziz</a>
        <a class="navbar-item" href="jfazio.php">James Fazio</a>
        <a class="navbar-item" href="kpollock.php">Kyle Pollock</a>
      </div>

    </div>

</nav>
