
<footer class="footer">

    <div class="pull-left">
        <div>By Zubair Aziz</div>
        <div>University of Rochester '19</div>
        <div><a href="mailto:zabaziz@u.rochester.edu">zabaziz@u.rochester.edu</a></div>

    </div>

    <div class="pull-right align-right">
        <div>Follow me on: </div>
        <div class="social">
            <a href="https://www.github.com/zubairaziz">
                <i class="fab fa-github" aria-hidden="true"></i>
            </a>
            <a href="https://www.linkedin.com/in/zubairabaziz/">
                <i class="fab fa-linkedin" aria-hidden="true"></i>
            </a>
            <a href="https://www.facebook.com/zubair0496">
                <i class="fab fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="https://www.instagram.com/zbr.aziz/?hl=en">
                <i class="fab fa-instagram" aria-hidden="true"></i>
            </a>
        </div>
    </div>

</footer>
